
version: '3.1'

services:

  db:
    # 数据库镜像使用 mariadb
    image: mariadb
    restart: always
    environment:
      # 配置 root 用户密码为 rootpw
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      # 将端口映射到本机
      - 3306:3306

  adminer:
    # adminer 是一个数据管理系统
    image: adminer
    restart: always
    ports:
      # 将 adminer 的端口映射到本机，便于访问
      - 8080:8080